namespace: huawei
name: cloudengine
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.netcommon: '>=1.0'
repository: git@github.com:coll-test/huawei.cloudengine.git
documentation: https://github.com/coll-test/huawei.cloudengine/tree/master/docs
homepage: https://github.com/coll-test/huawei.cloudengine
issues: https://github.com/coll-test/huawei.cloudengine/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
